"""Run snow_craft.py in parallel Blender slices (standard-library Python)."""

import argparse
from collections import Counter
import csv
import os
from pathlib import Path
import subprocess
import sys
import time


TOOLS = Path(__file__).resolve().parent
PROJECT = TOOLS.parent
WORKSPACE = PROJECT.parent.parent
BLENDER = TOOLS / 'ext/blender-4.5.9-windows-x64/blender.exe'
INDEX = PROJECT / 'source/SeasonZ/scripts/4_World/SeasonZ/SZ_BakedIndex.c'
DEFAULT_LOG = WORKSPACE / 'dayz-mission-audit/seasonz-mvp-20261004/craft_logs'
HEADER = ('name', 'shape', 'result', 'stats', 'secs')


def local_path(value):
    path = Path(value).resolve()
    if not path.is_relative_to(WORKSPACE):
        raise ValueError(f'Path is outside workspace: {path}')
    return path


def read_lines(path, offset=0):
    if not path.exists():
        return []
    with path.open('rb') as stream:
        stream.seek(offset)
        data = stream.read()
    # A worker may currently be writing the final line.
    return [line.decode('utf-8', errors='replace').rstrip('\r')
            for line in data.split(b'\n')[:-1] if line.strip()]


def read_rows(log_dir, offsets=None):
    rows, errors = [], []
    paths = sorted(log_dir.glob('craft_*.log')) if offsets is None else offsets
    for path in paths:
        for number, line in enumerate(read_lines(path, 0 if offsets is None else offsets[path]), 1):
            fields = line.split('\t')
            if len(fields) != 5:
                errors.append(f'Malformed log row: {path.name}:{number}: {line}')
                continue
            try:
                float(fields[4].removesuffix('s'))
            except ValueError:
                errors.append(f'Invalid duration: {path.name}:{number}: {line}')
                continue
            rows.append(fields)
    return rows, errors


def summarize(log_dir):
    rows, errors = read_rows(log_dir)
    with local_path(log_dir / 'craft_summary.tsv').open('w', encoding='utf-8', newline='') as stream:
        writer = csv.writer(stream, delimiter='\t', lineterminator='\r\n')
        writer.writerow(HEADER)
        writer.writerows(rows)
    counts = Counter('error' if row[2].startswith('error') else row[2] for row in rows)
    print('\nSummary (all craft_*.log rows):', flush=True)
    for result, count in sorted(counts.items()):
        print(f'  {result}: {count}')
    print('Slowest 15 models:')
    for row in sorted(rows, key=lambda row: float(row[4].removesuffix('s')), reverse=True)[:15]:
        print(f'  {row[0]}\t{row[2]}\t{row[4]}')
    print('Errors:')
    failures = ['\t'.join(row) for row in rows if row[2].startswith('error')]
    for message in errors + failures:
        print(f'  {message}')
    if not errors and not failures:
        print('  none')
    print(f'Summary file: {log_dir / "craft_summary.tsv"}', flush=True)
    return rows, errors


def index_entries(rows, out_dir):
    entries, errors = {}, []
    # If logs contain repeated models, the last recorded result wins.
    latest = {row[1]: row for row in rows}
    for shape, row in sorted(latest.items()):
        name, _, result, _, _ = row
        if result.startswith('ok'):
            if Path(name).name != name or '/' in name or '\\' in name:
                errors.append(f'Invalid model name: {name!r}')
                continue
            missing = [f'{name}_v{variant}.p3d' for variant in range(1, 8)
                       if not local_path(out_dir / f'{name}_v{variant}.p3d').is_file()]
            if missing:
                errors.append(f'Excluded {name}: missing {", ".join(missing)}')
                continue
            entries[shape] = name
        elif result in ('nosnow', 'notop', 'nofaces') or result.startswith('skip'):
            # no face of the model holds snow (signs, ropes, railings, decals, proxy-only tents): no snow at all,
            # rather than the sampled roof snow
            entries[shape] = '-'
    return entries, errors


def write_index(entries):
    lines = ['//! generated by tools/craft_all.py (snow_craft.py): the map models with baked snow (shape -> name of the models in data/baked; "-" = no snow)',
             'class SZ_BakedIndex', '{', '\tstatic void Fill(map<string, string> m)', '\t{']
    for shape, name in sorted(entries.items()):
        lines.append('\t\tm.Insert("%s", "%s");' % (shape.replace('\\', '\\\\'), name))
    lines += ['\t}', '}', '']
    target = local_path(INDEX)
    temporary = local_path(target.with_suffix('.c.tmp'))
    with temporary.open('w', encoding='utf-8', newline='\r\n') as stream:
        stream.write('\n'.join(lines))
    temporary.replace(target)
    print(f'Index: {len(entries)} entries -> {target}', flush=True)


def run(args):
    src, out_dir, log_dir = map(local_path, (args.szbake, args.out, args.log))
    if not src.is_dir():
        raise ValueError(f'Missing szbake directory: {src}')
    for required in (BLENDER, TOOLS / 'snow_craft.py'):
        if not required.is_file():
            raise ValueError(f'Missing required file: {required}')
    only = None
    if args.only is not None:
        only = [name.strip() for name in args.only.split(',')]
        if not all(only) or len(set(only)) != len(only):
            raise ValueError('--only requires distinct, nonempty model names')
    total = 0
    for path in sorted(src.glob('*.txt')):
        with path.open(encoding='latin-1') as stream:
            total += stream.readline().startswith('model ')
    if only is not None:
        total = len(only)
    if not total:
        raise ValueError('No models found; nothing was deleted')
    for directory in (out_dir, log_dir):
        if directory == src or directory in src.parents:
            raise ValueError(f'Output/log directory must not contain the input directory: {directory}')
        directory.mkdir(parents=True, exist_ok=True)
    env = os.environ.copy()
    for key, suffix in [('BLENDER_USER_CONFIG', 'config'), ('BLENDER_USER_SCRIPTS', 'scripts'),
                        ('BLENDER_USER_DATAFILES', 'data'), ('BLENDER_USER_EXTENSIONS', 'ext'),
                        ('TEMP', 'tmp'), ('TMP', 'tmp')]:
        directory = local_path(TOOLS / 'ext/bhome' / suffix)
        directory.mkdir(parents=True, exist_ok=True)
        env[key] = str(directory)
    env['PYTHONDONTWRITEBYTECODE'] = '1'
    # Validate every existing destination before deleting anything or launching workers.
    cleanup = list(out_dir.glob('*.p3d')) + list(log_dir.glob('craft_*.log'))
    for path in cleanup:
        local_path(path)
    offsets = {}
    for k in range(args.jobs):
        path = local_path(log_dir / f'craft_{k}.log')
        offsets[path] = path.stat().st_size if only is not None and path.exists() else 0
        local_path(log_dir / f'blender_{k}.txt')
    local_path(log_dir / 'craft_summary.tsv')
    if only is None:
        for path in cleanup:
            path.unlink()
    workers, outputs = [], []
    started = time.monotonic()
    try:
        for k in range(args.jobs):
            command = [str(BLENDER), '-b', '--factory-startup', '--python-exit-code', '1',
                       '--python', str(TOOLS / 'snow_craft.py'), '--', str(src), str(out_dir),
                       '--slice', f'{k}/{args.jobs}', '--log', str(log_dir)]
            if only is not None:
                command += ['--only', ','.join(only)]
            # Preserve previous diagnostic output for --only runs as well.
            stream = (log_dir / f'blender_{k}.txt').open('ab' if only is not None else 'wb')
            outputs.append(stream)
            workers.append(subprocess.Popen(command, cwd=PROJECT, env=env,
                                            stdout=stream, stderr=subprocess.STDOUT))
        previous, last_report = None, 0
        while True:
            active = sum(worker.poll() is None for worker in workers)
            completed = sum(len(read_lines(path, offset)) for path, offset in offsets.items())
            now = time.monotonic()
            state = (completed, active)
            if state != previous or now - last_report >= 15:
                print(f'Progress: {completed}/{total} models; {active}/{args.jobs} workers active; '
                      f'{now - started:.0f}s elapsed', flush=True)
                previous, last_report = state, now
            if not active:
                break
            time.sleep(1)
    finally:
        for worker in workers:
            if worker.poll() is None:
                worker.terminate()
        for worker in workers:
            try:
                worker.wait(timeout=10)
            except subprocess.TimeoutExpired:
                worker.kill()
                worker.wait()
        for stream in outputs:
            stream.close()
    rows, errors = summarize(log_dir)
    current, current_errors = read_rows(log_dir, offsets)
    errors += current_errors
    for k, worker in enumerate(workers):
        if worker.returncode:
            errors.append(f'Blender slice {k}/{args.jobs} exited with {worker.returncode}; see blender_{k}.txt')
    if len(current) != total:
        errors.append(f'Expected {total} current results, received {len(current)}')
    entries, missing = index_entries(current if only is not None else rows, out_dir)
    errors += missing
    if not args.no_index and only is None:
        write_index(entries)
    for message in errors:
        print(f'ERROR: {message}', file=sys.stderr, flush=True)
    # Unsupported/partial models are reported separately from process/runtime failures.
    return 1 if errors or any(row[2].startswith('error') for row in current) else 0


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('szbake', help='Directory containing szbake .txt exports')
    parser.add_argument('--out', default=str(PROJECT / 'source/SeasonZ/data/baked'))
    parser.add_argument('--log', default=str(DEFAULT_LOG))
    parser.add_argument('--jobs', type=int, default=12)
    parser.add_argument('--only', help='Comma-separated model names; preserves existing files and index')
    parser.add_argument('--no-index', action='store_true')
    args = parser.parse_args()
    if args.jobs < 1:
        parser.error('--jobs must be at least 1')
    try:
        return run(args)
    except KeyboardInterrupt:
        print('\nInterrupted; Blender workers stopped.', file=sys.stderr)
        return 130
    except (OSError, ValueError, subprocess.SubprocessError) as exc:
        print(f'ERROR: {exc}', file=sys.stderr)
        return 1


if __name__ == '__main__':
    sys.exit(main())
